name: Build and Push Docker Images and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy: # Zmieniona nazwa zadania na bardziej opisową
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ----------------------------------------------
      # 1. LOGOWANIE, BUDOWANIE I PUSHOWANIE OBRAZÓW (DO ACR)
      # ----------------------------------------------
      - name: Login to Azure Container Registry (ACR)
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # Build i Push Frontend
      - name: Build and Push frontend image
        run: |
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/uczelnia-frontend:latest -f frontend/Dockerfile ./frontend
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/uczelnia-frontend:latest

      # Build i Push Backend
      - name: Build and Push backend image
        run: |
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/uczelnia-backend:latest -f backend/Backend/Dockerfile ./backend/Backend
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/uczelnia-backend:latest

      # ----------------------------------------------
      # 2. DEPLOY FRONTEND (na kalkulatorfront)
      # ----------------------------------------------
      - name: Deploy frontend image to kalkulatorfront
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: kalkulatorfront
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          imageToDeploy: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/uczelnia-frontend:latest
          acrUsername: ${{ secrets.AZURE_ACR_USERNAME }}
          acrPassword: ${{ secrets.AZURE_ACR_PASSWORD }}

     # ----------------------------------------------
      # 3. DEPLOY BACKEND (na kalkulatorback)
      # ----------------------------------------------
      - name: Deploy backend image to kalkulatorback
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: kalkulator
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          imageToDeploy: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/uczelnia-backend:latest
          acrUsername: ${{ secrets.AZURE_ACR_USERNAME }}
          acrPassword: ${{ secrets.AZURE_ACR_PASSWORD }}